### ISSUE TITLE
Feature Request: Mermaid integration

### ISSUE THREAD

**Issue by berlincount** [arnehilmann/markdeck#11]
https://mermaidjs.github.io/ offers even more visualisation options for Flowcharts, Sequence diagrams, and also Gantt charts.

I haven't looked at markdeck's internals yet, so I don't know how big the effort would be, but I think this might be a worthwhile addition - also, we've got existing diagrams in this syntax, so it would be helpful to have, as compared to converting to graphviz.

Thank you for your consideration!

**Comment by arnehilmann** [comment]
In fact, mermaid is on my shortlist of tools-to-be-integrated-in-markdeck...
I will have a look into this in the next couple of days

**Comment by arnehilmann** [comment]
Please have a look at the new test-area:
https://github.com/arnehilmann/markdeck/tree/master/docs/docs/test-area/mermaid-test
That directory contains a minimal showcase for mermaid (and it features the new include mechanism `! INCLUDE "filename.here"` as well).

In short: it is already possible to use mermaid within markdeck. You just need a little bit more code, like this:
```
::: mermaid
```{=html}
graph LR
    A --- B
    B-->C[fa:fa-ban forbidden]
    B-->D(fa:fa-spinner);
```
:::

I think about beautifying this a little bit with a custom filter; the possible markdown would be something like this:

    ```render_mermaid
    ...
    ```

**Comment by arnehilmann** [comment]
mermaid integration improves with the next release: 0.51

**Comment by arnehilmann** [comment]
and here it is: v0.51...
