### ISSUE TITLE
How to not center text?

### ISSUE THREAD

**Issue by neilhwatson** [arnehilmann/markdeck#15]
How can the default behaviour of centring text be changed? I cannot find any examples in the docs.

**Comment by arnehilmann** [comment]
add the css class ```flush_text_left``` to the section, like this:
```
# my header {.flush_text_left}

text should appear on the left...
```

markdeck relies on the presentation framework `reveal.js`; 
so have a look [here](https://stackoverflow.com/questions/21019476/how-can-i-get-left-justified-paragraphs-in-reveal-js) also...

**Comment by neilhwatson** [comment]
For posterity I did this inside slides.md before the first slide.

```
<style type="text/css">
.reveal .slides { text-align: left; }

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 { text-align:  center; }
</style>
```
