### ISSUE TITLE
Define slide width

### ISSUE THREAD

**Issue by neilhwatson** [arnehilmann/markdeck#18]
How can the default slide width be changed, both singly and globally?

**Comment by jceb** [comment]
There is a width option in the defaults that can be overridden. Furthermore, you can adjust the PDF output size. Put the following in your sildes.md at the top and adjust the parameters as you like:
```
---
width: 960
height: 700
pdf_size: 1189x841
---
```

**Comment by arnehilmann** [comment]
@neilhwatson does this answer your question?
