### ISSUE TITLE
nav controls: boolean config parameters not parsed correctly

### ISSUE THREAD

**Issue by gerald1248** [arnehilmann/markdeck#2]
If I change the config defaults of the `example` slide deck I'm likely to run into errors.

For example -- having bumped the image tag from 0.18 to 0.20 -- I can render the example deck using `./render_example` and all is well.

If however I decide that I don't want page navigation to be visible and set `controls: false`, no output is produced. The browser shows error `Uncaught SyntaxError: Unexpected token ,` and any PDF also fails to render.

Oddly, when markdeck echoes back the configuration, boolean `true` in slides.md is shown without quotes, whereas `false` is quoted:
```
{
  "controls": false,
  "autoSlideMethod": "Reveal.navigateNext",
  "variant": "revealjs",
  "autoPlayMedia": "null",
  "shuffle": "false",
  "transition": "slide",
  "hideAddressBar": true,
  ...
}
```

**Comment by arnehilmann** [comment]
Please try it again with quotes around “false“.

**Comment by arnehilmann** [comment]
Config values “false“ and “null” must be quoted, otherwise they get ‘lost’ somewhere (hence the syntax error).
I will have a closer look when back at keyboard.
btw: “false” is the default for ‘controls’, so removing/commenting this config might help, too...

**Comment by gerald1248** [comment]
Closing as really "not a bug", thanks!
