### ISSUE TITLE
CI integration for pages

### ISSUE THREAD

**Issue by asmodehn** [arnehilmann/markdeck#21]
Maybe I am missing something here...but I tried to find an example of CI integration around and failed.

What I have in mind is a flow Github commit -> Travis build -> Github pages commit.
So that one can have github pages hosting a markdeck presentation.

Or is there a reason why this workflow would not be appropriate ? 

Note I haven't tried myself just yet, unsure how docker-compose would play with travis environment...

**Comment by arnehilmann** [comment]
One of the ideas behind `markdeck` is the possibility to preview your slides _before_ you have to check in your changes. I once had to collaborate with an online slide-deck generator, triggered by git commits: more than 50% of the first 400 commits dealt with obvious syntax errors and minor layout issues :o(
It was possible to configure markdeck to run in a one-shot mode, I should investigate that again... 
But if the docker env of travis and the markdeck containers play along nicely is still another question thou...

**Comment by asmodehn** [comment]
Thank you for the information, good to know...
The docker setup locally didnt work for me either but I didnt investigate
further just yet.
