### ISSUE TITLE
Does work image rendering?

### ISSUE THREAD

**Issue by sebelk** [arnehilmann/markdeck#22]
I've tried to include images without no success, for example:

`!(My image)[myimage.jpg]`

and with

`!(My image)(./myimage.jpg]`

none of them works... :) it results in HTTP 404 error... am I missing something? is it a bug?

Thanks in advance!

**Comment by sebelk** [comment]
I've just found it! images must go into deck folder :)
HTH

**Comment by arnehilmann** [comment]
No. Don't put anything into the deck folder manually, it may be overwritten/removed at any time.
To integrate images and other assets, put them in the `assets` folder an reference them there, i.e.:
`!(my image)[assets/myimage.png]`
everything under `assets` gets synced to the `deck` folder.

**Comment by sebelk** [comment]
It would be nice that it was documented :)
