### ISSUE TITLE
Text tool not working in AsciiFlow

### ISSUE THREAD

**Issue by sebelk** [arnehilmann/markdeck#23]
In the version included of AsciiFlow, the text tool does not work. However it does work on AsciiFlow upstream version. I've tried on Firefox, Chromium, Falkon, Konqueror, and on all of them have the same problem.

Thanks in advance

**Comment by arnehilmann** [comment]
Interesting... obviously I never used the text tool.
I will have a look, but it isn't very high on my prio list...

**Comment by arnehilmann** [comment]
should work in the freshly released v0.50...

BTW:  the markdown-friends (fka markdeck-helper) live as standalone image: https://hub.docker.com/repository/docker/arne/markdown-friends
