### ISSUE TITLE
asciitosvg is in maintenance mode

### ISSUE THREAD

**Issue by sebelk** [arnehilmann/markdeck#24]
I've found that [dhobsd/asciitosvg](https://github.com/dhobsd/asciitosvg) is in maintenance mode. Perhaps [http://github.com/asciitosvg/asciitosvg](http://github.com/asciitosvg/asciitosvg) should be used instead.

Greetings

**Comment by arnehilmann** [comment]
Yeah, I know... it is for quite a time now...
the new version you mentioned looks really promising, but still lacks the support for custom shapes; and I like those. so for now, I will continue to use the old php implementation...
