### ISSUE TITLE
Ascii art: Problem with accents

### ISSUE THREAD

**Issue by sebelk** [arnehilmann/markdeck#25]
Words with accents are bad-rendered, for example:

```render_a2s
#----------------------.
|[Introducción a Linux]|
'----------------------#
[Introducción a Linux]: {"fill": "Teal", "fillStyle": "solid"}
```

it results in:

![imagen](https://user-images.githubusercontent.com/4109256/58591202-214f3b00-823c-11e9-8dd0-e31b4e3f34cf.png)

Note the "]"

If I replace "ó" by "o" it renders ok without that triling "]"

Any ideas?

Thanks in advance!

**Comment by arnehilmann** [comment]
The underlying tool `ditta` is a bit older, and might have some issues with unicode rendering.
Sorry, but right now I have no idea on how to fix that...
markdeck uses `https://github.com/pepijnve/ditaa`, which is a fork of
`https://github.com/stathissideris/ditaa`; perhaps you can find some help there?!
