### ISSUE TITLE
Styling doesn't seem to work

### ISSUE THREAD

**Issue by xixixao** [arnehilmann/markdeck#39]
This project is great! But I couldn't figure out how to change the styles, changing the .sass file and even restarting markdeck didn't work.

Not depending on docker would be great too.

**Comment by jceb** [comment]
Have you tried creating the project with `markdeck scaffold`? There should be a style sheet in `assets/css/slides.scss` that you can adjust to your liking. In addition, you have the option to create a theme in `assets/css/theme/`. The latter follows reveal.js' standard. I hope that helps.

Regarding docker: yes, that would be great.

**Comment by arnehilmann** [comment]
@xixixao does jceb's comment answered your question?

**Comment by xixixao** [comment]
I moved to use vanilla revealjs, so haven't had a chance to try, sorry.
