### ISSUE TITLE
Speaker notes view not working as expected

### ISSUE THREAD

**Issue by gerald1248** [arnehilmann/markdeck#42]
I'm using the latest (v0.51) build of markdeck on Catilina 10.15.5.

If I add speaker notes to any slide (by adding an `<aside>` element with class "notes" and the data-markdown pseudo attribute), the notes appear on each page even when there are no notes, and the 's' toggle does not seem to work, nor does the presentation screen open.

All this worked absolutely fine in earlier versions (with `start` script).

[markdeck-speaker-notes-issue.zip](https://github.com/arnehilmann/markdeck/files/4932343/markdeck-speaker-notes-issue.zip)

**Comment by arnehilmann** [comment]
fixed with v0.52.2
