### ISSUE TITLE
support for vertical slides

### ISSUE THREAD

**Issue by dmastag** [arnehilmann/markdeck#47]
I would like to have vertical slides. Is that currently possible using markdeck?

**Comment by arnehilmann** [comment]
If you use the default framework (reveal.js), just add vertical slides with a level 2 heading, like this:
```
# top title

## subslide 1

## subslide 2
```

when using impress.js (by specifying `variant: impress` in the metadata section), you can have vertical, tilted, rotated, and zoomed slides as you wish (but beware the roller coaster effect).
