### ISSUE TITLE
Missing themes folder

### ISSUE THREAD

**Issue by dmastag** [arnehilmann/markdeck#48]
Looks like yesterday's update broke something

I am getting the following error
`ERROR: for src_markdeck_1  Cannot create container for service markdeck: invalid mount config for type "bind": invalid mount path: 'deck/.empty' mount path must be absolute`

Which can be solved after adding the themes folder.

**Comment by arnehilmann** [comment]
okay, v0.53.2 was a little bit rushed, I am afraid...

**Comment by arnehilmann** [comment]
should work with v0.53.4
