### ISSUE TITLE
no .pdf output

### ISSUE THREAD

**Issue by Xalphor** [arnehilmann/markdeck#52]
Hey,

I love the project and I've been doing all my presentations with it for the last four years. And yet I've never really needed the .pdf outputfile.. Until now. With most of my past presentations I could just set the "pdf: XXX.pdf" option in the config at the start of my slides.md file and markdeck would automatically render my presentation with decktape and give me the output. But no matter how hard I try, I can't get my .pdf file this time. 

Is there another thing I need to do to get markdeck to render a pdf?

Or can I just render it manually? (JS noob here tho, so I can't get decktape to work on my machine) 

May the problem be that I am running archlinux?

And finally: Is there any log output you need that could help you help me?

This is kind of urgent, because I need the .pdf for a collage exam. 

Thanks a lot in advance! 
Best regards,
Holger

**Comment by arnehilmann** [comment]
Hi!
Do you use the latest version?
And did you start markdeck with `./markdeck start pdf`?

**Comment by Xalphor** [comment]
Thanks so much for the quick reply!

I am using the latest version but I didn't start markdeck with the pdf option on.

I just used ```markdeck``` or ```markdeck start```. 
Is the ```pdf``` option somewhere in the documentation? In that case I am just blind I think. However it worked and I am beyond happy!

Thank again,
Holger

**Comment by arnehilmann** [comment]
Glad to hear that!
Documentation of the (now optional) services? Good point, that might be still missing *hüstel*
