### ISSUE TITLE
Font too small on homepage

### ISSUE THREAD

**Issue by Gitleptune** [arnehilmann/markdeck#55]
Problem: The font on the home page is way too small to be readable by most people, let alone people with disabilities.

![image](https://user-images.githubusercontent.com/76597257/126050143-015ac926-6078-4c44-9988-4ce6d2233060.png)

Fix: Increase font size

**Comment by arnehilmann** [comment]
You are right; I just refurbished and streamlined the landing page a bit, it should look better on smaller devices now...
