### ISSUE TITLE
PDF not generated but no error logged

### ISSUE THREAD

**Issue by AndyDentFree** [arnehilmann/markdeck#56]
I did a presentation using the deck at https://github.com/AndyDentFree/DDDlottie21 and **thanks for all your work** as it went very smoothly. 

But, unlike the last time I used markdeck, in 2019, I'm not seeing a PDF generated.

The config parsing from the `slides.md` seems to have parsed the PDF directive, judging from the attached log:

`"pdf": "WholeLottieToolsDDD21.pdf"`

[logRerenderButNoPDF.txt](https://github.com/arnehilmann/markdeck/files/6987613/logRerenderButNoPDF.txt)

How can I diagnose what's going wrong?

**Comment by arnehilmann** [comment]
(I should really update the documentation in that regard)

Please try `markdeck start pdf`.

**Comment by arnehilmann** [comment]
Please feel free to reopen this issue if the above comment does not help you.
